kind: Service
apiVersion: v1
metadata:
  name:  svc-letmask
spec:
  selector:
    app:  letmask
  type: NodePort
  ports:
  - name:  letmask
    port:  80
    nodePort:  30000
  selector:
    app: letmask