on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  

name: marcos

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ env.AWS_REGION }}

    - name: Aplication dependency
      run:  npm install

    - name: Aplication build
      run:  npm run build

    # - name: S3 bucket
    #   run:  cd dist && aws s3 cp ./ s3://letmeask --recursive

    - name: Deploy letmeask
      run: echo deploy success